"""Regression guard for the shared color/mono framing policy.

Compares current render output against tests/unify_baseline.json, regenerated by
_capture_baseline() below. EVERY case in the matrix is frozen: both pipelines run one
policy (compose upright for the frame; a crop forces cover; else the single
crop_to_fill_threshold), so any byte movement is a real framing change.

The snapshot was re-captured on refactor/remove-auto-rotate-fit — deleting the toggle
changed every orientation-mismatch case by design (nothing composes sideways any more),
so the original pre-unify baseline could not carry over.

Determinism note: color output is only reproducible with dither_noise=0.0 (see the
capture module); with the default preset noise the bytes are random and this guard
is meaningless. To re-baseline deliberately (e.g. a legitimate Pillow change), run
this module directly: `python tests/test_unify_regression_guard.py`.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

import tests._unify_baseline_capture as cap  # noqa: E402  (test-support module)

_BASELINE_PATH = Path(__file__).parent / "unify_baseline.json"


def _load_frozen() -> dict[str, str]:
    data = json.loads(_BASELINE_PATH.read_text())
    return data["frozen"]


@pytest.fixture(scope="module")
def current():
    return cap.capture_all()


@pytest.mark.parametrize("key", sorted(_load_frozen()))
def test_frozen_render_output_unchanged(key, current):
    frozen = _load_frozen()
    assert current[key] == frozen[key], (
        f"{key}: baseline {frozen[key]} != current {current[key]}. Framing changed for a "
        f"case the snapshot freezes. If this is a deliberate, reviewed change, re-baseline: "
        f"python tests/test_unify_regression_guard.py"
    )


def test_baseline_is_complete_and_frozen_only():
    """The snapshot contains exactly the frozen cases — no changing case leaked in."""
    frozen = _load_frozen()
    expected = {k for k in cap.capture_all() if cap.is_frozen(k)}
    assert set(frozen) == expected


def _capture_baseline():
    """Rewrite unify_baseline.json from CURRENT code. Verifies determinism first."""
    a = cap.capture_all()
    b = cap.capture_all()
    diff = {k for k in a if a[k] != b[k]}
    if diff:
        raise SystemExit(f"non-deterministic capture, refusing to baseline: {sorted(diff)}")
    frozen = {k: v for k, v in a.items() if cap.is_frozen(k)}
    _BASELINE_PATH.write_text(json.dumps({"frozen": frozen}, indent=1, sort_keys=True))
    print(f"re-baselined {len(frozen)} frozen cases -> {_BASELINE_PATH.name}")


if __name__ == "__main__":
    _capture_baseline()
